name: Build AAC Encoder Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libavcodec-dev libavutil-dev libc++-dev libc++abi-dev
      - name: Build plugin
        run: |
          make clean && make
          ./build.sh
      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp -r aac_encoder_plugin.dvcp.bundle artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aac_encoder_plugin-bundle
          path: artifact/aac_encoder_plugin.dvcp.bundle
